### ISSUE TITLE
How to display array number in Fidelity_Auto.side?

### ISSUE THREAD

**Issue by sunk818** [Prem-ium/Auto-StockTrader#18]
index value is 0 when script starts. As it loops through the accounts, it increments by one. Is there a way to display what number the script is on? I recall there's a way to manually continue from a mid-point if we know the index number where we replace the index 0 to another integer to continue mid-way.

**Comment by Prem-ium** [comment]
Hello Sunk,

I'm not certain of what exactly you are asking. The array value should already be printing in echo statements as the script iterates through the accounts. The purpose of the `index` variable in `Fidelity_Auto.side` currently is to separate account arrays for users with multiple logins. The variable is assigned to 0 by default as most users will only have one list to plug in. 

In order to continue mid-way through on any of the existing scripts, all you need to do is enter the last successful array value or index into the `target` variable and let the script slice your array for you starting at the next point. I will integrate a counter in new versions to possibly alter this to take a counter starting point instead.
