### ISSUE TITLE
Select account in Schwab

### ISSUE THREAD

**Issue by debilin** [Prem-ium/Auto-StockTrader#28]
Is there a way to select specific account in Charles Schwab for trading?  I only see an option to set the total number of accounts.  If not, can this feature be added.

**Comment by debilin** [comment]
Since TD Ameritrade has now been merged into Schwab, I now have 2 brokerage accounts in Schwab.  However, I only want to use one of these for trading activity.  Is this how most people trade? Or most people trade in all accounts at the same time?

**Comment by Prem-ium** [comment]
@debilin 
Most people use it to trade in all accounts, but if since you only have two accounts you should be able to do it easily. If you prefer to only use the tool on your first account (from the dropdown menu on Schwab's trading webpage), set your `SCHWAB_AI` env variable to equal one. Otherwise, if you want to use only your second account, you can assign set it to 2 & assign the 'target' variable inside of Selenium IDE to 0.
